questions=(
    "¿Cuál de los siguientes es un principio clave del software de código abierto?"
    "¿Qué comando se utiliza para mostrar la ruta absoluta del directorio actual?"
    "¿Qué organización es responsable de mantener el kernel de Linux?"
    "¿Qué comando se utiliza para buscar una cadena de texto dentro de un archivo?"
    "¿Qué licencia es más comúnmente utilizada para el kernel de Linux?"
    "¿Cuál es el propósito del archivo /etc/passwd en un sistema Linux?"
    "¿Qué operador se utiliza para redirigir la salida estándar a un archivo?"
    "¿Qué componente es responsable de la gestión de hardware en un sistema Linux?"
    "¿Qué comando se utiliza para cambiar los permisos de un archivo en Linux?"
    "¿Qué símbolo representa el directorio raíz en un sistema Linux?"
    "¿Qué gestor de arranque es comúnmente utilizado en sistemas Linux?"
    "¿Cuál es el rol principal de una distribución de Linux?"
    "¿Qué comando muestra información sobre el uso de memoria en tiempo real?"
    "¿Qué atajo de teclado detiene un proceso en ejecución en la terminal?"
    "¿Qué tipo de archivo es representado por una 'd' en la salida del comando ls -l?"
    "¿Qué herramienta se utiliza para gestionar paquetes en distribuciones basadas en Debian?"
    "¿Qué comando se utiliza para concatenar y mostrar el contenido de un archivo?"
    "¿Qué es el archivo /proc en Linux?"
    "¿Qué comando muestra la cantidad de espacio usado por un directorio?"
    "¿Cuál es la representación octal de los permisos rwxr-xr--?"
    "¿Qué comando permite ver los procesos ejecutándose actualmente en el sistema?"
    "¿Qué archivo contiene las contraseñas cifradas de los usuarios en Linux?"
    "¿Qué comando se utiliza para listar los archivos en un directorio?"
    "¿Qué comando se utiliza para cambiar el propietario de un archivo?"
    "¿Qué archivo en Linux se utiliza para configurar el entorno de usuario?"
    "¿Qué comando se utiliza para verificar el espacio libre en disco en Linux?"
    "¿Qué comando muestra información de red en Linux?"
    "¿Cuál es el propósito del archivo /etc/shadow en Linux?"
    "¿Qué símbolo se utiliza para representar el directorio home del usuario?"
    "¿Qué comando se utiliza para crear un enlace simbólico en Linux?"
    "¿Qué comando muestra el contenido de un archivo paginado?"
    "¿Qué licencia de software es compatible con la filosofía de código abierto?"
    "¿Qué comando se utiliza para mostrar la ruta del directorio actual?"
    "¿Qué archivo en Linux almacena información acerca de las particiones montadas?"
    "¿Qué comando se utiliza para detener un servicio en ejecución?"
    "¿Qué significa el permiso 'x' en un archivo en Linux?"
    "¿Qué comando muestra estadísticas de CPU y memoria en tiempo real?"
    "¿Qué símbolo se utiliza para concatenar dos comandos en Bash?"
    "¿Qué comando se utiliza para cambiar al directorio padre del actual?"
    "¿Qué archivo en Linux registra los intentos de inicio de sesión fallidos?"
)

options=(
    "a) Software privativo\nb) Interfaz de usuario\nc) Transparencia\nd) Acceso restringido"
    "a) pwd\nb) ls\nc) cd\nd) echo"
    "a) Canonical\nb) The Linux Foundation\nc) Free Software Foundation\nd) Microsoft"
    "a) find\nb) grep\nc) locate\nd) echo"
    "a) MIT\nb) Apache License\nc) GPLv2\nd) BSD"
    "a) Almacena contraseñas cifradas\nb) Contiene la configuración del sistema\nc) Almacena información de usuarios\nd) Contiene scripts de arranque"
    "a) >\nb) |\nc) &&\nd) ||"
    "a) Sistema de archivos\nb) Shell\nc) Kernel\nd) BIOS"
    "a) chmod\nb) chown\nc) ls -l\nd) umask"
    "a) /\nb) ~\nc) .\nd) /home"
    "a) GRUB\nb) LILO\nc) UEFI\nd) MBR"
    "a) Distribuir hardware\nb) Facilitar la instalación del sistema\nc) Gestionar redes\nd) Crear aplicaciones"
    "a) top\nb) free\nc) vmstat\nd) htop"
    "a) Ctrl+Z\nb) Ctrl+C\nc) Ctrl+D\nd) Ctrl+X"
    "a) Archivo\nb) Enlace simbólico\nc) Directorio\nd) Archivo ejecutable"
    "a) yum\nb) apt\nc) pacman\nd) rpm"
    "a) cat\nb) echo\nc) touch\nd) ls"
    "a) Archivo binario\nb) Sistema de archivos virtual\nc) Registro de usuarios\nd) Configuración del sistema"
    "a) df\nb) du\nc) fdisk\nd) mount"
    "a) 644\nb) 754\nc) 755\nd) 744"
    "a) ps\nb) top\nc) free\nd) vmstat"
    "a) /etc/passwd\nb) /etc/shadow\nc) /var/log\nd) /tmp"
    "a) cat\nb) ls\nc) cp\nd) mv"
    "a) chmod\nb) chown\nc) mv\nd) cp"
    "a) /etc/profile\nb) /etc/shadow\nc) /home/user/.bashrc\nd) /tmp"
    "a) df\nb) du\nc) ls\nd) free"
    "a) netstat\nb) ip\nc) ifconfig\nd) ping"
    "a) Almacena contraseñas cifradas\nb) Registro de actividades\nc) Configuración de red\nd) Almacenamiento temporal"
    "a) /\nb) ~\nc) .\nd) /home"
    "a) ln\nb) link\nc) touch\nd) mkdir"
    "a) more\nb) less\nc) head\nd) tail"
    "a) GPL\nb) MIT\nc) Apache\nd) BSD"
    "a) pwd\nb) ls\nc) cd\nd) mkdir"
    "a) /etc/fstab\nb) /proc/partitions\nc) /boot/grub\nd) /var/log"
    "a) systemctl stop\nb) kill\nc) shutdown\nd) exit"
    "a) Lectura\nb) Escritura\nc) Ejecución\nd) Eliminación"
    "a) top\nb) free\nc) htop\nd) df"
    "a) ;\nb) &&\nc) |\nd) >"
    "a) cd ..\nb) cd /\nc) cd ~\nd) cd /root"
    "a) /var/log/auth.log\nb) /etc/shadow\nc) /home/.bashrc\nd) /var/run"
)

correct_answers=(
    "c" "a" "b" "b" "c"
    "c" "a" "c" "a" "a"
    "a" "b" "b" "b" "c"
    "b" "a" "b" "b" "c"
    "b" "b" "b" "b" "a"
    "a" "b" "a" "b" "a"
    "b" "a" "a" "a" "a"
    "c" "a" "c" "c" "a"
)